version: 2
updates:
- package-ecosystem: nuget
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: System.IdentityModel.Tokens.Jwt
    versions:
    - 6.10.0
    - 6.10.1
    - 6.10.2
  - dependency-name: IdentityModel
    versions:
    - 5.0.1
  - dependency-name: System.Text.Json
    versions:
    - 5.0.1
